# Generated by Django 3.2.8 on 2021-11-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'not placed'), ('1', 'placed'), ('2', 'ready'), ('3', 'delivered')], default='', max_length=1),
        ),
    ]
