# Generated by Django 3.2.8 on 2021-11-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
