# Generated by Django 3.2.8 on 2021-11-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_delivery_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.delivery'),
        ),
    ]
