# Generated by Django 3.2.8 on 2021-11-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
