# Generated by Django 3.2.8 on 2021-11-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_delivery_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
