# Generated by Django 3.2.8 on 2021-11-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_delivery_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
