# Generated by Django 3.2.8 on 2021-11-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_delivery_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='restaurant',
        ),
    ]
