# Generated by Django 3.2.8 on 2021-11-13 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_remove_delivery_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
