# Generated by Django 3.2.8 on 2021-11-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_delivery_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
